name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run tests and capture output
      run: |
        python main.py > test_output.txt || echo "Test failed" > napaka.txt

    - name: Check for errors
      run: |
        if [ -f "napaka.txt" ]; then
          cat napaka.txt
          exit 1
        fi
