name: Test

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
      continue-on-error: true

  run-tests:
    runs-on: self-hosted
    needs: setup-environment
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run tests and capture output
      run: |
        python test_script.py > test_output.txt || echo "Test failed" > napaka.txt

    - name: Check for errors
      run: |
        if [ -f "napaka.txt" ]; then
          touch napaka.txt
          exit 1
        fi
