name: Test

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        touch napaka.txt
        python -m pip install --upgrade pip > pip_install_log.txt 2>&1 || echo "Napaka pri pip." > napaka.txt
        pip install -r requirements.txt > requirements_install_log.txt 2>&1 || echo "Napaka pri req" > napaka.txt
    
    - name: Error msg
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: errors
        path: napaka.txt
        if-no-files-found: ignore
        

  run-tests:
    runs-on: self-hosted
    needs: setup-environment
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout code
      uses: actions/download-artifact@v2
      with:
        name: errors    
    - name: Run tests and capture output
      run: |
        if [ -s napaka.txt ]; then
          echo "Env not set up correctly"
          cat napaka.txt
          exit 1
        else
          echo "Code testing"
        fi
    - name: Pytesting
      run: pytest
